# Generated by Django 3.2.25 on 2024-07-31 05:55

import datetime

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("brand", models.CharField(max_length=32)),
                ("model", models.CharField(max_length=32)),
                ("year_of_production", models.DateField(default=datetime.date(2020, 1, 1))),
                ("car_mileage", models.PositiveIntegerField(default=1000)),
                (
                    "type",
                    models.CharField(
                        choices=[("sedan", "Sedan"), ("suv", "SUV"), ("coupe", "Couple")],
                        default="sedan",
                        max_length=32,
                    ),
                ),
                (
                    "transmission_type",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        default="auto",
                        max_length=8,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("gas", "Gas"), ("diesel", "Diesel")], default="gas", max_length=8
                    ),
                ),
                (
                    "passengers",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "2+"), (4, "4+"), (5, "5+"), (7, "7+")], default=4
                    ),
                ),
                ("investor_daily_price", models.PositiveSmallIntegerField()),
                ("manager_daily_price", models.PositiveSmallIntegerField()),
                ("post_service_duration", models.PositiveSmallIntegerField(default=0)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("image", models.FileField(upload_to="vehicles/")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicle.vehicle",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
