# Generated by Django 3.2.25 on 2024-08-02 13:06

import pyuploadcare.dj.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleimage",
            name="image",
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
