# Generated by Django 4.2.15 on 2024-08-18 15:38

import uuid

import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("daily_price", models.PositiveSmallIntegerField()),
                ("client_name", models.CharField(max_length=256)),
                (
                    "client_phone",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="geo.city"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="vehicle.vehicle",
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
    ]
