# Generated by Django 3.2.25 on 2024-08-13 13:58

import uuid

from django.db import migrations
from django.db import models


def populate_uuid(Model):
    for obj in Model.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=("uuid",))


def populate_vehicle_uuid(apps, schema_editor):
    Vehicle = apps.get_model("vehicle", "Vehicle")
    populate_uuid(Vehicle)


def populate_image_uuid(apps, schema_editor):
    Image = apps.get_model("vehicle", "VehicleImage")
    populate_uuid(Image)


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0002_alter_vehicleimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="uuid",
            field=models.UUIDField(editable=False, unique=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleimage",
            name="uuid",
            field=models.UUIDField(editable=False, unique=True, null=True),
        ),
        migrations.RunPython(populate_vehicle_uuid, migrations.RunPython.noop),
        migrations.RunPython(populate_image_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="vehicle",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicleimage",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
