# Generated by Django 3.2.25 on 2024-08-14 19:34

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
        ("vehicle", "0003_auto_20240813_1358"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="city",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="geo.city"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geo.country",
            ),
        ),
    ]
