# Generated by Django 3.2.25 on 2024-08-15 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="country",
            name="uuid",
        ),
    ]
