VEHICLE_TYPE_SEDAN = "sedan"
VEHICLE_TYPE_SUV = "suv"
VEHICLE_TYPE_COUPE = "coupe"

VEHICLE_TYPES = (
    (VEHICLE_TYPE_SEDAN, "Sedan"),
    (VEHICLE_TYPE_SUV, "SUV"),
    (VEHICLE_TYPE_COUPE, "Couple"),
)


GEARSHIFT_TYPE_AUTO = "auto"
GEARSHIFT_TYPE_MANUAL = "manual"

GEARSHIFT_TYPES = (
    (GEARSHIFT_TYPE_AUTO, "Automatic"),
    (GEARSHIFT_TYPE_MANUAL, "Manual"),
)

PASSENGERS_2 = 2
PASSENGERS_4 = 4
PASSENGERS_5 = 5
PASSENGERS_7 = 7

PASSENGERS_TYPES = (
    (PASSENGERS_2, "2+"),
    (PASSENGERS_4, "4+"),
    (PASSENGERS_5, "5+"),
    (PASSENGERS_7, "7+"),
)
